// GRINLOUD — Track data, radar data, video pool
// Plain JS (no ES modules): exposes window.GRINLOUD_DATA

// ── NEWSLETTER CONFIG (Beehiiv) ───────────────────────────────────────────
// 1. Create account at beehiiv.com
// 2. Settings → API → create key (scope: Write) → paste below
// 3. Settings → Publication → copy Publication ID → paste below
const NEWSLETTER = {
  publicationId: 'pub_5e1017ca-29b9-4f13-8608-8494ef117408',
  // API key lives in Cloudflare Pages env vars — never exposed to browser
};

const BG_VIDEOS = [
  'grok-video-0af53696-e3d9-496b-9ac4-14fe2d60da8b.mp4',
  'grok-video-0af53696-e3d9-496b-9ac4-14fe2d60da8b-2.mp4',
  'grok-video-0af53696-e3d9-496b-9ac4-14fe2d60da8b-3.mp4',
  'grok-video-0af53696-e3d9-496b-9ac4-14fe2d60da8b-4.mp4',
  'grok-video-0af53696-e3d9-496b-9ac4-14fe2d60da8b-5.mp4',
  'grok-video-0af53696-e3d9-496b-9ac4-14fe2d60da8b-6.mp4',
  'grok-video-0af53696-e3d9-496b-9ac4-14fe2d60da8b-7.mp4',
  'grok-video-0af53696-e3d9-496b-9ac4-14fe2d60da8b-8.mp4',
  'grok-video-0af53696-e3d9-496b-9ac4-14fe2d60da8b-9.mp4',
  'grok-video-3527a3e1-5b5d-4e52-8be0-893e21832cce.mp4',
  'grok-video-3527a3e1-5b5d-4e52-8be0-893e21832cce-2.mp4',
  'grok-video-3527a3e1-5b5d-4e52-8be0-893e21832cce-3.mp4',
  'grok-video-3527a3e1-5b5d-4e52-8be0-893e21832cce-4.mp4',
  'grok-video-3527a3e1-5b5d-4e52-8be0-893e21832cce-5.mp4',
  'grok-video-3527a3e1-5b5d-4e52-8be0-893e21832cce-6.mp4',
  'grok-video-3527a3e1-5b5d-4e52-8be0-893e21832cce-7.mp4',
  'grok-video-3527a3e1-5b5d-4e52-8be0-893e21832cce-8.mp4',
  'grok-video-3527a3e1-5b5d-4e52-8be0-893e21832cce-9.mp4',
  'grok-video-3527a3e1-5b5d-4e52-8be0-893e21832cce-10.mp4',
  'grok-video-8d63d04f-de4b-456a-b683-bc6f53e731be.mp4',
  'grok-video-8d63d04f-de4b-456a-b683-bc6f53e731be-2.mp4',
  'grok-video-8d63d04f-de4b-456a-b683-bc6f53e731be-3.mp4',
  'grok-video-8d63d04f-de4b-456a-b683-bc6f53e731be-4.mp4',
  'grok-video-8d63d04f-de4b-456a-b683-bc6f53e731be-5.mp4',
  'grok-video-aa6e4151-d13d-4a2b-a3be-35db84e5059e.mp4',
  'grok-video-aa6e4151-d13d-4a2b-a3be-35db84e5059e-2.mp4',
  // ── Parkhaus series — Music Radar 005 picks ──
  'parkhaus-001.mp4',
  'parkhaus-002.mp4',
  'parkhaus-003.mp4',
  'parkhaus-004.mp4',
  'parkhaus-005.mp4',
  'parkhaus-006.mp4',
  'parkhaus-007.mp4',
  'parkhaus-008.mp4',
  'parkhaus-009.mp4',
  'parkhaus-010.mp4',
];

// Picks — newest first (index 0 = most recent)
// Videos distributed cyclically across the 26 available loops.
const PICKS = [

  // ── MUSIC RADAR 005 — 01–10 Jun 2026 ──────────────────────────────────────
  {
    id: 'pick-2026-06-10',
    date: '2026-06-10',
    title: 'Alcoholic',
    artist: 'SAN PACHO',
    bpm: 132, key: 'Eb Major', label: 'LIBERA', release: '10 Jun 2026',
    genre: 'Tech House', accent: 'pink', video: BG_VIDEOS[35],
    info: "San Pacho on LIBERA closes 005 in style. Alcoholic is the kind of track that keeps going long after the night ends.",
    short: "Keeps going long after the night ends.",
    links: { spotify: 'https://open.spotify.com/track/5Iedc3D20KJoj95uQRp5p0', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-06-09',
    date: '2026-06-09',
    title: 'Bad Wolf',
    artist: 'MICHAEL BIBI',
    bpm: 131, key: 'Ab Major', label: 'EMPIRE', release: '09 Jun 2026',
    genre: 'Tech House', accent: 'pink', video: BG_VIDEOS[34],
    info: "Bibi on EMPIRE. Bad Wolf has teeth — dark, muscular, completely in control. One of his sharpest.",
    short: "Dark, muscular, completely in control.",
    links: { spotify: 'https://open.spotify.com/track/4S8bYzrUHwoAsPzJWRt4QM', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-06-08',
    date: '2026-06-08',
    title: 'Control',
    artist: 'AFROJACK, LUCAS & STEVE',
    bpm: 130, key: 'Ab Major', label: 'Black Book Records', release: '08 Jun 2026',
    genre: 'Tech House', accent: 'pink', video: BG_VIDEOS[33],
    info: "Afrojack steps into Tech House territory on Black Book Records and doesn't miss. Control is smooth, relentless, and impossible to ignore.",
    short: "Smooth and relentless. Afrojack doesn't miss.",
    links: { spotify: 'https://open.spotify.com/track/4e1L2pH75XOtCE0I0XzxlU', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-06-07',
    date: '2026-06-07',
    title: 'Waist Move',
    artist: 'GREG 99',
    bpm: 130, key: 'Eb Major', label: 'Nervous Records', release: '07 Jun 2026',
    genre: 'Tech House', accent: 'pink', video: BG_VIDEOS[32],
    info: "GREG 99 builds something infectious — a groove that takes over the floor before you even realise it's happening.",
    short: "A groove that takes over before you realise it.",
    links: { spotify: 'https://open.spotify.com/track/7HzUjBSzXpS3vsmz8VG7yW', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-06-06',
    date: '2026-06-06',
    title: 'Rake It Up',
    artist: 'KENZ (US)',
    bpm: 130, key: 'Gb Major', label: 'Repopulate Mars', release: '06 Jun 2026',
    genre: 'Tech House', accent: 'pink', video: BG_VIDEOS[31],
    info: "KENZ on Repopulate Mars. Rake It Up has the swagger of a late-night set closer — minimal but fully loaded.",
    short: "The swagger of a late-night set closer.",
    links: { spotify: 'https://open.spotify.com/track/6YNRSnDi92sAhYO8XzonVT', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-06-05',
    date: '2026-06-05',
    title: 'Rich & Handsome',
    artist: 'MATRODA, SAN PACHO & AF:MN',
    bpm: 130, key: 'Ab Minor', label: 'AFTER MIDNIGHT', release: '05 Jun 2026',
    genre: 'Tech House', accent: 'pink', video: BG_VIDEOS[30],
    info: "Three names, one weapon. Matroda, San Pacho and AFTER MIDNIGHT deliver something slick, dark and impossible to ignore.",
    short: "Slick, dark and impossible to ignore.",
    links: { spotify: 'https://open.spotify.com/track/1oeljccOyFQGPOY8gaVnnH', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-06-04',
    date: '2026-06-04',
    title: 'So Hot!',
    artist: 'JAKE BLEU & EDRIS OMAR',
    bpm: 128, key: 'B Minor', label: 'House Rules Records', release: '04 Jun 2026',
    genre: 'Tech House', accent: 'pink', video: BG_VIDEOS[29],
    info: "Does exactly what it says. Jake Bleu and Edris Omar turn up the temperature without breaking a sweat.",
    short: "Turns up the temperature without breaking a sweat.",
    links: { spotify: 'https://open.spotify.com/track/5Tpca7PbJGQpPUJohnFStN', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-06-03',
    date: '2026-06-03',
    title: 'Lipstick',
    artist: 'ALAIA & GALLO',
    bpm: 128, key: 'D Minor', label: 'Toolroom', release: '03 Jun 2026',
    genre: 'Tech House', accent: 'pink', video: BG_VIDEOS[28],
    info: "Toolroom's finest doing what they do best. Lipstick is proper floor-first Tech House — tight, punchy, and impossible to shake.",
    short: "Proper floor-first Tech House. Tight and impossible to shake.",
    links: { spotify: 'https://open.spotify.com/track/5DeNvGYijFobt2ufPFGhsK', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-06-02',
    date: '2026-06-02',
    title: 'Take Control',
    artist: 'LOOZBONE',
    bpm: 130, key: 'G Minor', label: 'Catch & Release', release: '02 Jun 2026',
    genre: 'Tech House', accent: 'pink', video: BG_VIDEOS[27],
    info: "LOOZBONE locks in on Catch & Release with a groove that doesn't let go. The bass takes the wheel and the floor follows.",
    short: "The bass takes the wheel and the floor follows.",
    links: { spotify: 'https://open.spotify.com/track/0ucs704ejvx402bCbDC7ms', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-06-01',
    date: '2026-06-01',
    title: 'Army',
    artist: 'QOBRA (IT)',
    bpm: 128, key: 'C Minor', label: 'The Myth of NYX', release: '01 Jun 2026',
    genre: 'Tech House', accent: 'pink', video: BG_VIDEOS[26],
    info: "Dark and relentless. Qobra builds a room-ready Tech House weapon from scratch — no filler, no mercy. Opens 005 exactly right.",
    short: "Dark and relentless. No filler, no mercy.",
    links: { spotify: 'https://open.spotify.com/track/75386mOXWOPoHCjNRc3rgj', youtube: '#', beatport: '#', soundcloud: '#' }
  },

  // ── MUSIC RADAR 004 — 22–31 May 2026 ──────────────────────────────────────
  {
    id: 'pick-2026-05-31',
    date: '2026-05-31',
    title: 'Seratonin',
    artist: 'JAMES HYPE',
    bpm: 138,
    key: 'F Minor',
    label: 'Island Records',
    release: '31 May 2026',
    genre: 'Dance / Pop',
    accent: 'yellow',
    video: BG_VIDEOS[0],
    info: "James Hype closes the month with pure euphoria. Seratonin is exactly what it promises — a rush that peaks the floor and doesn't apologise.",
    short: "James Hype closes the month with pure euphoria.",
    links: { spotify: 'https://open.spotify.com/track/0SZKacJ8DMFQjmdUfSJX2C', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-30',
    date: '2026-05-30',
    title: 'Function',
    artist: 'SIDEPIECE',
    bpm: 132,
    key: 'D Minor',
    label: 'Experts Only',
    release: '30 May 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[1],
    info: "SIDEPIECE at peak form. Function is what happens when two of tech house's sharpest are fully locked in.",
    short: "SIDEPIECE at peak form.",
    links: { spotify: 'https://open.spotify.com/track/1bhRw5feZyeh5Ti0o40wC9', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-29',
    date: '2026-05-29',
    title: 'The Past, The Present, The Future',
    artist: 'DAVID GUETTA & MARTEN HØRGER',
    bpm: 132,
    key: 'F Major',
    label: "Spinnin' Records",
    release: '29 May 2026',
    genre: 'Bass House',
    accent: 'blue',
    video: BG_VIDEOS[2],
    info: "Guetta and Hørger's Men Machine alias drops. Coachella-tested, bass-driven, electro-tinged. The future sounds like this.",
    short: "Coachella-tested, bass-driven, electro-tinged.",
    links: { spotify: 'https://open.spotify.com/track/1Cp8mfSFvYo7ddTy7NkmpL', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-28',
    date: '2026-05-28',
    title: 'Turn Up The Bass',
    artist: 'ALESSO & JOA FT. TYREE COOPER',
    bpm: 130,
    key: 'Gb Major',
    label: 'Body Hi',
    release: '28 May 2026',
    genre: 'Dance / Pop',
    accent: 'yellow',
    video: BG_VIDEOS[3],
    info: "Alesso and JOA flip Tyree Cooper's 1988 Chicago classic into a 2026 thunderer. Bass-heavy, synth-loaded, full circle.",
    short: "A 1988 Chicago classic flipped into a 2026 thunderer.",
    links: { spotify: 'https://open.spotify.com/track/4YtKvo2pTZsy8kCq9A7d8c', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-27',
    date: '2026-05-27',
    title: "Don't Stop",
    artist: 'PROSPA',
    bpm: 130,
    key: '—',
    label: 'Insomniac',
    release: '27 May 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[4],
    info: "Prospa is everywhere right now and Don't Stop is the reason. Clean, energetic, completely relentless.",
    short: "Clean, energetic, completely relentless.",
    links: { spotify: 'https://open.spotify.com/track/13cX2o4cASGLYXNaQyXWxt', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-26',
    date: '2026-05-26',
    title: 'My Own Thang (To The Beat)',
    artist: 'WALKER & ROYCE, ALOK & SOPHIEGROPHY',
    bpm: 130,
    key: 'G Minor',
    label: 'Hellbent Records',
    release: '26 May 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[5],
    info: 'Walker & Royce bring swagger, Alok brings Brazilian heat. Rolling tech house that keeps moving.',
    short: 'Walker & Royce bring swagger, Alok brings Brazilian heat.',
    links: { spotify: 'https://open.spotify.com/track/675XtSIBWY5q5D5lxdp40M', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-25',
    date: '2026-05-25',
    title: 'Dancing Boys, Dancing Girls',
    artist: 'ODD MOB',
    bpm: 130,
    key: 'G Minor',
    label: 'Insomniac',
    release: '25 May 2026',
    genre: 'Bass House',
    accent: 'blue',
    video: BG_VIDEOS[6],
    info: "Odd Mob hits Beatport Bass House top 5. Made for floors that don't discriminate.",
    short: "Made for floors that don't discriminate.",
    links: { spotify: 'https://open.spotify.com/track/6i7J4zXJU7ZQVuLfb9bPGD', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-24',
    date: '2026-05-24',
    title: 'Hands Up',
    artist: 'VOLKODER & VINTAGE CULTURE',
    bpm: 128,
    key: 'Db Minor',
    label: 'AFFAIRS',
    release: '24 May 2026',
    genre: 'Tech House',
    accent: 'orange',
    video: BG_VIDEOS[7],
    info: 'Vintage Culture and Volkoder Ultra-road-tested this before the world heard it. Hands go up, no questions asked.',
    short: 'Ultra-road-tested. Hands go up, no questions asked.',
    links: { spotify: 'https://open.spotify.com/track/2X3MVthrKaaP8RbrEen8UJ', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-23',
    date: '2026-05-23',
    title: "Can't Sleep",
    artist: 'TONY ROMERA',
    bpm: 126,
    key: 'F Minor',
    label: "Sound D'Elite",
    release: '23 May 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[8],
    info: "Tony Romera is relentless. Can't Sleep doesn't let you rest — rolling bass, locked groove, no exits.",
    short: "Rolling bass, locked groove, no exits.",
    links: { spotify: 'https://open.spotify.com/track/1j2iVhhHif1dMifGtQhwUa', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-22',
    date: '2026-05-22',
    title: 'Addicted',
    artist: 'KUNGS & CHANEY',
    bpm: 126,
    key: 'A Minor',
    label: 'Universal Music',
    release: '22 May 2026',
    genre: 'Dance / Pop',
    accent: 'yellow',
    video: BG_VIDEOS[9],
    info: 'Kungs and CHANEY deliver a deep, seductive club cut. Addicted is effortless in the best way — warm, hypnotic, impossible to put down.',
    short: 'Warm, hypnotic, impossible to put down.',
    links: { spotify: 'https://open.spotify.com/track/0GqORtXPbb3BuYJhkarOYp', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-21',
    date: '2026-05-21',
    title: 'Turn Up The Dose',
    artist: 'KREAM & SCRIPT',
    bpm: 130,
    key: 'D Major',
    label: 'Liquid Lab',
    release: '21 May 2026',
    genre: 'Bass House',
    accent: 'blue',
    video: BG_VIDEOS[10],
    info: 'KREAM and Script prescribe exactly what the dancefloor needs. Punishing bass, surgical drops, zero recovery time. Take the full dose.',
    short: 'Punishing bass, surgical drops, zero recovery time.',
    links: { spotify: 'https://open.spotify.com/track/4IIb4DQxNBAowpUJmKYNMD', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-20',
    date: '2026-05-20',
    title: "She's A Devil",
    artist: 'LAYTON GIORDANI & AR/CO',
    bpm: 130,
    key: 'D Minor',
    label: 'Experts Only',
    release: '20 May 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[11],
    info: "Layton Giordani teams up with AR/CO for something darkly seductive. She's A Devil earns its name — tempting, dangerous, and impossible to resist.",
    short: "Darkly seductive. Tempting, dangerous, impossible to resist.",
    links: { spotify: 'https://open.spotify.com/track/0RGoQAGnUlFkKcaCta4vmH', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-19',
    date: '2026-05-19',
    title: 'Dança',
    artist: 'KC LIGHTS',
    bpm: 128,
    key: 'Db Minor',
    label: 'Toolroom',
    release: '19 May 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[12],
    info: 'KC Lights brings infectious Latin flair to the Toolroom stable. Dança is warm, percussive, and impossible to stand still to — proper peak-hour material.',
    short: 'Warm, percussive, impossible to stand still to.',
    links: { spotify: 'https://open.spotify.com/track/1bSEok2LJmdLzaIYAj14bk', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-18',
    date: '2026-05-18',
    title: 'Attack',
    artist: 'GREGGIO',
    bpm: 128,
    key: 'A Major',
    label: 'Nu Moda',
    release: '18 May 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[13],
    info: "The title isn't a suggestion. Greggio goes straight for the jugular — a precision-built tech house weapon with zero filler and maximum impact.",
    short: "Precision-built tech house weapon. Zero filler, maximum impact.",
    links: { spotify: 'https://open.spotify.com/track/44vqflfNrPLnAW1Y5B1e4c', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-17',
    date: '2026-05-17',
    title: 'Mind Alert',
    artist: 'MOJJO & CAIQUE CARVALHO',
    bpm: 127,
    key: 'G Major',
    label: 'Hellbent Records',
    release: '17 May 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[14],
    info: 'Brazilian energy meets underground club discipline. Mind Alert hits that sweet spot between cerebral and physical — your body moves before your brain catches up.',
    short: 'Your body moves before your brain catches up.',
    links: { spotify: 'https://open.spotify.com/track/69mO0n022H0cggGm85wYZw', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-16',
    date: '2026-05-16',
    title: "Let's Freak",
    artist: 'RSQUARED & IGLESIAS',
    bpm: 130,
    key: 'C Major',
    label: 'RWorks',
    release: '16 May 2026',
    genre: 'Bass House',
    accent: 'blue',
    video: BG_VIDEOS[15],
    info: 'Does exactly what it says. No apologies, no buildup, straight to the point. Bass house at its most unapologetic.',
    short: 'Bass house at its most unapologetic.',
    links: { spotify: 'https://open.spotify.com/track/2PM8jCZ2lnC1YTHkiQC8Rl', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-15',
    date: '2026-05-15',
    title: 'Like That',
    artist: 'MARCO FARAONE',
    bpm: 130,
    key: 'F Major',
    label: 'Nervous Records',
    release: '15 May 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[16],
    info: "Faraone doesn't waste a single bar. Tight, driving, purposeful — this is what tech house sounds like when someone truly understands the dancefloor.",
    short: "Tight, driving, purposeful. Not a bar wasted.",
    links: { spotify: 'https://open.spotify.com/track/2G9EQucmyuipl9wXCO1oNx', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-14',
    date: '2026-05-14',
    title: 'Loaded Gun',
    artist: 'CID',
    bpm: 129,
    key: 'F Major',
    label: 'Insomniac',
    release: '14 May 2026',
    genre: 'Bass House',
    accent: 'blue',
    video: BG_VIDEOS[17],
    info: 'CID loads the chamber and fires. Pure bass house aggression wrapped in a deceptively clean package. Festival-ready from the first bar.',
    short: 'Pure bass house aggression. Festival-ready from bar one.',
    links: { spotify: 'https://open.spotify.com/track/19PBU0nWYBOMzHOAxDBEcg', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-13',
    date: '2026-05-13',
    title: 'Baby',
    artist: 'FOUR TET & TONY ROMERA',
    bpm: 129,
    key: 'D Major',
    label: 'Text Records',
    release: '13 May 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[18],
    info: 'Four Tet steps into tech house territory with Tony Romera and the result is something unexpected — warm, weird, and deeply groovy. Two worlds colliding perfectly.',
    short: 'Warm, weird, and deeply groovy. Two worlds colliding perfectly.',
    links: { spotify: 'https://open.spotify.com/track/1ArFwgEU2iQMq9dU43sGZ9', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-12',
    date: '2026-05-12',
    title: 'Stunner',
    artist: 'DEEPER PURPOSE, JACK ORLEY & MICHAEL EKOW',
    bpm: 128,
    key: 'D Major',
    label: 'IN 2 DEEP',
    release: '12 May 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[19],
    info: 'Deeper Purpose teams up with Jack Orley and Michael Ekow for a hypnotic tech house groover. Dark, surgical, and relentless — the kind of track that builds tension until the room breaks.',
    short: 'Dark, surgical, relentless. The room breaks.',
    links: { spotify: 'https://open.spotify.com/track/6RmHESttla4I4g4vr0NLkQ', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-11',
    date: '2026-05-11',
    title: "Actin' Tough",
    artist: 'DEAN TURNLEY',
    bpm: 140,
    key: 'Ab Major',
    label: 'CHAOS / ROSSI',
    release: '11 May 2026',
    genre: 'House',
    accent: 'yellow',
    video: BG_VIDEOS[20],
    info: 'Started as a Melbourne secret weapon. Spread globally via set clips before anyone knew the name. Peggy Gou, Chris Lake, Interplanetary Criminal — they all played it.',
    short: 'Melbourne secret weapon. Everyone played it.',
    links: { spotify: 'https://open.spotify.com/track/507j66jaEEUU11uFSTOHFM', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-10',
    date: '2026-05-10',
    title: 'Slay To The Rhythm',
    artist: 'NOIZU',
    bpm: 129,
    key: 'F Minor',
    label: 'Catch & Release',
    release: '10 May 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[21],
    info: "FISHER's label doesn't miss, and Noizu doesn't miss. A relentless groove machine with enough swagger to carry an entire set.",
    short: "A relentless groove machine with enough swagger to carry an entire set.",
    links: { spotify: 'https://open.spotify.com/track/6l5L3mJwDFqNsizPysrCNo', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-09',
    date: '2026-05-09',
    title: 'Make You Fight',
    artist: 'CHRIS LAKE × ATRIP',
    bpm: 131,
    key: 'G Minor',
    label: 'Black Book Records',
    release: '09 May 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[22],
    info: 'The long-teased ID that had fans chasing clips for months finally dropped. Hypnotic, relentless, and built to break rooms.',
    short: 'Hypnotic, relentless, built to break rooms.',
    links: { spotify: 'https://open.spotify.com/track/5di9ztnBe0d2qim9ngmiMD', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-08',
    date: '2026-05-08',
    title: "Don't Worry Baby",
    artist: 'DOM DOLLA × TIGA',
    bpm: 132,
    key: 'G Major',
    label: 'Three Six Zero Recordings',
    release: '08 May 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[23],
    info: 'Two dance music heavyweights debut together with a cosmic sci-fi trip. Road-tested at Coachella before anyone heard the studio version.',
    short: 'Cosmic sci-fi trip. Road-tested at Coachella.',
    links: { spotify: 'https://open.spotify.com/track/0uFffwji3muqn5MEe7hiYw', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-07',
    date: '2026-05-07',
    title: "In This Bih'",
    artist: 'CHRIS LORENZO × KAH-LO',
    bpm: 130,
    key: 'F# Major',
    label: 'Turbo Blanco',
    release: '07 May 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[24],
    info: 'Lorenzo and Kah-lo — two artists who understand exactly where the line between cool and commercial is, and dance right on top of it. Effortless.',
    short: 'Dancing right on the line between cool and commercial.',
    links: { spotify: 'https://open.spotify.com/track/4QUxlbwlSBYiaTT27A5MEj', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-06',
    date: '2026-05-06',
    title: 'Rock The Rhythm (I Like That)',
    artist: 'ODD MOB FEAT. LUCIANA',
    bpm: 132,
    key: 'F# Minor',
    label: 'October Records',
    release: '06 May 2026',
    genre: 'Bass House',
    accent: 'blue',
    video: BG_VIDEOS[25],
    info: "Melbourne's underground king flips a classic into something entirely his own. Luciana's vocal is the hook that won't leave — warm, punchy, undeniable.",
    short: "Luciana's vocal is the hook that won't leave.",
    links: { spotify: 'https://open.spotify.com/track/5XmCNo1dh4HjMjBAcBrrC5', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-05',
    date: '2026-05-05',
    title: 'Hots 4 U',
    artist: 'CHRIS LORENZO × AMO (UM)',
    bpm: 130,
    key: 'B Minor',
    label: 'Three Six Zero Recordings',
    release: '05 May 2026',
    genre: 'House',
    accent: 'yellow',
    video: BG_VIDEOS[0],
    info: 'The 100th release on tszr — and they went all in. A track born from 20 years of house music history, cut for today\'s dancefloors.',
    short: 'Born from 20 years of house music history.',
    links: { spotify: 'https://open.spotify.com/track/5nMrR3Ed99WcQ4Vv0wy8Bf', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-04',
    date: '2026-05-04',
    title: 'Passion (R U Satisfied)',
    artist: 'BELTRAN × THE FLIRTS',
    bpm: 127,
    key: 'E Major',
    label: 'Altra Moda Music',
    release: '04 May 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[1],
    info: "Two years as a secret weapon in Beltran's sets — the ID that everyone was hunting. Finally released and it hits exactly as hard as the clips promised.",
    short: "The ID everyone was hunting. It hits as hard as the clips promised.",
    links: { spotify: 'https://open.spotify.com/track/6XqRL8W59LbyLuIQ7wyjON', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-03',
    date: '2026-05-03',
    title: 'She A Freak',
    artist: 'ARMIN VAN BUUREN × SKYTECH',
    bpm: 130,
    key: 'Eb Minor',
    label: 'Armada Music',
    release: '03 May 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[2],
    info: '25 years of A State of Trance — and Armin picks this moment to go full tech house. Darker, groovier, more muscular than anything he\'s dropped in years. Road-tested at Ultra and Coachella.',
    short: "Armin goes full tech house. Darker, groovier, more muscular.",
    links: { spotify: 'https://open.spotify.com/track/2g0ZRPCjm3SEQYs5uFsQhP', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-02',
    date: '2026-05-02',
    title: 'Bad Angel',
    artist: 'ANYMA × LISA',
    bpm: 128,
    key: 'C Minor',
    label: 'Interscope Records',
    release: '02 May 2026',
    genre: 'Melodic House',
    accent: 'green',
    video: BG_VIDEOS[3],
    info: "Afterlife meets K-pop. Anyma brought LISA into his ÆDENverse — two worlds colliding into something cinematic and future-forward. Premiered at Coachella Mainstage with LISA's live surprise appearance.",
    short: "Afterlife meets K-pop. Cinematic and future-forward.",
    links: { spotify: 'https://open.spotify.com/track/4QR40LqFAbMdabh4AoZJGZ', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-05-01',
    date: '2026-05-01',
    title: 'Back To The 305',
    artist: 'OMAR+, LUKE DEAN',
    bpm: 126,
    key: 'F Major',
    label: 'Repopulate Mars',
    release: '01 May 2026',
    genre: 'House',
    accent: 'yellow',
    video: BG_VIDEOS[4],
    info: 'A love letter to Miami house culture. Back To The 305 has the warmth and groove of a classic with the production of something built for right now.',
    short: 'A love letter to Miami house culture.',
    links: { spotify: 'https://open.spotify.com/track/1tWkiHe2UtNye350uhqwVm', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-04-30',
    date: '2026-04-30',
    title: 'One More (feat. Ad-Apt)',
    artist: 'MAX STYLER, AD-APT, SOLOMUN',
    bpm: 124,
    key: 'D Minor',
    label: 'Diynamic',
    release: '30 Apr 2026',
    genre: 'Melodic House',
    accent: 'green',
    video: BG_VIDEOS[5],
    info: "Solomun's presence elevates everything. One More is melodic, warm, and quietly devastating — the kind of track you feel before you understand it.",
    short: "Melodic, warm, and quietly devastating.",
    links: { spotify: 'https://open.spotify.com/track/7hOwCb0vcnpNRBQUoI5smE', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-04-29',
    date: '2026-04-29',
    title: 'Neck',
    artist: 'MAU P',
    bpm: 131,
    key: 'G Minor',
    label: 'Tomorrowland Music',
    release: '29 Apr 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[6],
    info: 'Mau P is relentless and Neck is the proof. Dark groove, unexpected structure, maximum dancefloor intent. One of his best.',
    short: 'Dark groove, unexpected structure, maximum intent.',
    links: { spotify: 'https://open.spotify.com/track/6KrrcOQiX7NQ4h038wKTUy', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-04-28',
    date: '2026-04-28',
    title: 'How Does It Feel',
    artist: 'DUBDOGZ, FEZZO, ZAARK',
    bpm: 130,
    key: 'E Minor',
    label: 'Spinnin Records',
    release: '28 Apr 2026',
    genre: 'Bass House',
    accent: 'blue',
    video: BG_VIDEOS[7],
    info: 'Brazilian bass energy at full force. Dubdogz knows exactly how to build tension and release it — How Does It Feel does both with precision.',
    short: 'Brazilian bass energy at full force.',
    links: { spotify: 'https://open.spotify.com/track/0XJzkaWALsvlMEQbBSEIX2', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-04-27',
    date: '2026-04-27',
    title: 'All The Time',
    artist: 'JOHN SUMMIT, THE CHAINSMOKERS',
    bpm: 128,
    key: 'A Major',
    label: 'Experts Only',
    release: '27 Apr 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[8],
    info: 'An unlikely collab that works. Summit brings the underground credibility, The Chainsmokers bring the hook. All The Time lands exactly where it aims.',
    short: 'Underground credibility meets the hook. It lands exactly where it aims.',
    links: { spotify: 'https://open.spotify.com/track/1V8eQfZ1zpcdA9ctIb6fY7', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-04-26',
    date: '2026-04-26',
    title: 'Addicted To Bass',
    artist: 'DOM DOLLA, PURETONE',
    bpm: 130,
    key: 'C Minor',
    label: 'Sweat It Out',
    release: '26 Apr 2026',
    genre: 'Bass House',
    accent: 'blue',
    video: BG_VIDEOS[9],
    info: 'Dom Dolla flips a classic into something entirely contemporary. Addicted To Bass hits like a statement — and it is.',
    short: 'Dom Dolla flips a classic. Hits like a statement.',
    links: { spotify: 'https://open.spotify.com/track/0umvGSFCXSyrHGcXKwsvCg', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-04-25',
    date: '2026-04-25',
    title: 'Freaky 1',
    artist: 'MAX STYLER, VINTAGE CULTURE',
    bpm: 129,
    key: 'D Minor',
    label: 'Bizarre',
    release: '25 Apr 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[10],
    info: 'Max Styler and Vintage Culture lock in together on a track that earns its name. Freaky 1 is bold, elastic, and built for peak hour.',
    short: 'Bold, elastic, and built for peak hour.',
    links: { spotify: 'https://open.spotify.com/track/5cefCIhgIJgsG3r3LcRmwB', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-04-24',
    date: '2026-04-24',
    title: 'Talk To You',
    artist: 'ANOTR, 54 ULTRA',
    bpm: 126,
    key: 'F Minor',
    label: 'Repopulate Mars',
    release: '24 Apr 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[11],
    info: 'ANOTR continues their streak of effortlessly cool house music. Talk To You is groovy, understated, and impossible to ignore on a good soundsystem.',
    short: 'Groovy, understated, impossible to ignore on a good soundsystem.',
    links: { spotify: 'https://open.spotify.com/track/0kl6Ozan3fuUdCl6TlB15v', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-04-23',
    date: '2026-04-23',
    title: 'Free Your Mind',
    artist: 'TIËSTO, LUCAS & STEVE',
    bpm: 128,
    key: 'G Major',
    label: 'Musical Freedom',
    release: '23 Apr 2026',
    genre: 'Progressive House',
    accent: 'green',
    video: BG_VIDEOS[12],
    info: 'Tiësto teams up with Lucas & Steve and the result is pure euphoria. Free Your Mind is anthemic without being obvious — a rare balance in modern house.',
    short: 'Anthemic without being obvious. Pure euphoria.',
    links: { spotify: 'https://open.spotify.com/track/4KXq783lFLVnmC9dkI7j7l', youtube: '#', beatport: '#', soundcloud: '#' }
  },
  {
    id: 'pick-2026-04-22',
    date: '2026-04-22',
    title: 'Trigger Finger',
    artist: 'JAMES HYPE',
    bpm: 128,
    key: 'A Minor',
    label: 'Positiva',
    release: '22 Apr 2026',
    genre: 'Tech House',
    accent: 'pink',
    video: BG_VIDEOS[13],
    info: 'James Hype strips it back to pure instinct. Trigger Finger is minimal, muscular, and merciless — the kind of track that resets a room with a single drop.',
    short: 'Minimal, muscular, merciless. Resets a room with a single drop.',
    links: { spotify: 'https://open.spotify.com/track/0lXUyVhxuJOchIjOsVNkIj', youtube: '#', beatport: '#', soundcloud: '#' }
  },
];


// ── CURRENT RADAR — 005 (mix pending, YouTube TBA) ────────────────────────
const RADAR = {
  id: 'radar-005',
  number: '005',
  title: 'Music Radar 005',
  subtitle: 'Pure Club. Zero Filler.',
  date: '01 JUN 2026',
  nextDate: '11 JUN 2026',
  youtubeId: 'vikb1UGrUhI',
  duration: 'TBA',
  tracks: [
    { n: '01', title: 'Army',             artist: 'Qobra (IT)',                      bpm: 128, key: 'C Minor',  genre: 'Tech House', cue: '00:00' },
    { n: '02', title: 'Take Control',     artist: 'LOOZBONE',                        bpm: 130, key: 'G Minor',  genre: 'Tech House', cue: '00:00' },
    { n: '03', title: 'Lipstick',         artist: 'Alaia & Gallo',                   bpm: 128, key: 'D Minor',  genre: 'Tech House', cue: '00:00' },
    { n: '04', title: 'So Hot!',          artist: 'Jake Bleu & Edris Omar',          bpm: 128, key: 'B Minor',  genre: 'Tech House', cue: '00:00' },
    { n: '05', title: 'Rich & Handsome',  artist: 'Matroda, San Pacho & AF:MN',      bpm: 130, key: 'Ab Minor', genre: 'Tech House', cue: '00:00' },
    { n: '06', title: 'Rake It Up',       artist: 'KENZ (US)',                       bpm: 130, key: 'Gb Major', genre: 'Tech House', cue: '00:00' },
    { n: '07', title: 'Waist Move',       artist: 'GREG 99',                         bpm: 130, key: 'Eb Major', genre: 'Tech House', cue: '00:00' },
    { n: '08', title: 'Control',          artist: 'Afrojack, Lucas & Steve',         bpm: 130, key: 'Ab Major', genre: 'Tech House', cue: '00:00' },
    { n: '09', title: 'Bad Wolf',         artist: 'Michael Bibi',                    bpm: 131, key: 'Ab Major', genre: 'Tech House', cue: '00:00' },
    { n: '10', title: 'Alcoholic',        artist: 'San Pacho',                       bpm: 132, key: 'Eb Major', genre: 'Tech House', cue: '00:00' },
  ]
};


// ── PREVIOUS RADARS — newest first ────────────────────────────────────────
// tracks arrays use same shape as RADAR.tracks: {n, title, artist, bpm, key, genre, cue}
const PREVIOUS_RADARS = [
  {
    number: '004',
    title: 'Music Radar 004',
    subtitle: 'Ten tracks. Ten days. All killer.',
    date: '22 MAY 2026',
    nextDate: '01 JUN 2026',
    duration: '~60 MIN',
    youtubeId: 'fzcpYJV_jGk',
    spotifyUrl: 'https://open.spotify.com/playlist/5pwS4zMbmMb9WAOQhdPLTQ',
    tracks: [
      { n: '01', title: 'Addicted',                          artist: 'Kungs & CHANEY',                     bpm: 126, key: 'A Minor',  genre: 'Dance / Pop', cue: '00:00' },
      { n: '02', title: "Can't Sleep",                       artist: 'Tony Romera',                        bpm: 126, key: 'F Minor',  genre: 'Tech House',  cue: '00:00' },
      { n: '03', title: 'Hands Up',                          artist: 'Volkoder & Vintage Culture',         bpm: 128, key: 'Db Minor', genre: 'Tech House',  cue: '00:00' },
      { n: '04', title: 'Dancing Boys, Dancing Girls',       artist: 'Odd Mob',                            bpm: 130, key: 'G Minor',  genre: 'Bass House',  cue: '00:00' },
      { n: '05', title: 'My Own Thang (To The Beat)',        artist: 'Walker & Royce, Alok & Sophiegrophy', bpm: 130, key: 'G Minor', genre: 'Tech House',  cue: '00:00' },
      { n: '06', title: "Don't Stop",                        artist: 'Prospa',                             bpm: 130, key: '—',        genre: 'Tech House',  cue: '00:00' },
      { n: '07', title: 'Turn Up The Bass',                  artist: 'Alesso & JOA ft. Tyree Cooper',      bpm: 130, key: 'Gb Major', genre: 'Dance / Pop', cue: '00:00' },
      { n: '08', title: 'The Past, The Present, The Future', artist: 'David Guetta & Marten Hørger',       bpm: 132, key: 'F Major',  genre: 'Bass House',  cue: '00:00' },
      { n: '09', title: 'Function',                          artist: 'SIDEPIECE',                          bpm: 132, key: 'D Minor',  genre: 'Tech House',  cue: '00:00' },
      { n: '10', title: 'Seratonin',                         artist: 'James Hype',                         bpm: 138, key: 'F Minor',  genre: 'Dance / Pop', cue: '00:00' },
    ]
  },
  {
    number: '003',
    title: 'Music Radar 003',
    subtitle: 'Pure energy. No filler.',
    date: '12 MAY 2026',
    nextDate: '22 MAY 2026',
    duration: 'TBA',
    youtubeId: '0KoCRLzwS9Q',
    spotifyUrl: 'https://open.spotify.com/playlist/4XgZXcRJtaB1dYqPg3TGe6',
    tracks: [
      { n: '01', title: 'Stunner',          artist: 'Deeper Purpose, Jack Orley & Michael Ekow', bpm: 128, key: 'D Major',  genre: 'Tech House',  cue: '00:00' },
      { n: '02', title: 'Baby',             artist: 'Four Tet & Tony Romera',                    bpm: 129, key: 'D Major',  genre: 'Tech House',  cue: '00:00' },
      { n: '03', title: 'Loaded Gun',       artist: 'CID',                                       bpm: 129, key: 'F Major',  genre: 'Bass House',  cue: '00:00' },
      { n: '04', title: 'Like That',        artist: 'Marco Faraone',                             bpm: 130, key: 'F Major',  genre: 'Tech House',  cue: '00:00' },
      { n: '05', title: "Let's Freak",      artist: 'RSquared & Iglesias',                       bpm: 130, key: 'C Major',  genre: 'Bass House',  cue: '00:00' },
      { n: '06', title: 'Mind Alert',       artist: 'Mojjo & Caique Carvalho',                   bpm: 127, key: 'G Major',  genre: 'Tech House',  cue: '00:00' },
      { n: '07', title: 'Attack',           artist: 'Greggio',                                   bpm: 128, key: 'A Major',  genre: 'Tech House',  cue: '00:00' },
      { n: '08', title: 'Dança',            artist: 'KC Lights',                                 bpm: 128, key: 'Db Minor', genre: 'Tech House',  cue: '00:00' },
      { n: '09', title: "She's A Devil",    artist: 'Layton Giordani & AR/CO',                   bpm: 130, key: 'D Minor',  genre: 'Tech House',  cue: '00:00' },
      { n: '10', title: 'Turn Up The Dose', artist: 'KREAM & Script',                            bpm: 130, key: 'D Major',  genre: 'Bass House',  cue: '00:00' },
    ]
  },
  {
    number: '002',
    title: 'Music Radar 002',
    subtitle: 'No blog. No template.',
    date: '02 MAY 2026',
    nextDate: '12 MAY 2026',
    duration: 'TBA',
    youtubeId: '2e4103lR-KY',
    spotifyUrl: 'https://open.spotify.com/playlist/0jwYLN2HBrxNaji5AiSinW',
    tracks: [
      { n: '01', title: 'Bad Angel',              artist: 'Anyma & LISA',                bpm: 128, key: 'C Minor',  genre: 'Melodic House', cue: '00:00' },
      { n: '02', title: 'She A Freak',            artist: 'Armin van Buuren & Skytech',  bpm: 130, key: 'Eb Minor', genre: 'Tech House',    cue: '00:00' },
      { n: '03', title: 'Passion (R U Satisfied)', artist: 'Beltran & The Flirts',       bpm: 127, key: 'E Major',  genre: 'Tech House',    cue: '00:00' },
      { n: '04', title: 'Hots 4 U',              artist: 'Chris Lorenzo & AMO',          bpm: 130, key: 'B Minor',  genre: 'House',         cue: '00:00' },
      { n: '05', title: 'Rock The Rhythm',        artist: 'Odd Mob feat. Luciana',       bpm: 132, key: 'F# Minor', genre: 'Bass House',    cue: '00:00' },
      { n: '06', title: "In This Bih'",           artist: 'Chris Lorenzo & Kah-Lo',      bpm: 130, key: 'F# Major', genre: 'Tech House',    cue: '00:00' },
      { n: '07', title: "Don't Worry Baby",       artist: 'Dom Dolla & Tiga',            bpm: 132, key: 'G Major',  genre: 'Tech House',    cue: '00:00' },
      { n: '08', title: 'Make You Fight',         artist: 'Chris Lake & ATRIP',          bpm: 131, key: 'G Minor',  genre: 'Tech House',    cue: '00:00' },
      { n: '09', title: 'Slay To The Rhythm',     artist: 'Noizu',                       bpm: 129, key: 'F Minor',  genre: 'Tech House',    cue: '00:00' },
      { n: '10', title: "Actin' Tough",           artist: 'Dean Turnley',                bpm: 140, key: 'Ab Major', genre: 'House',         cue: '00:00' },
    ]
  },
  {
    number: '001',
    title: 'Music Radar 001',
    subtitle: 'Where it started.',
    date: '22 APR 2026',
    nextDate: '02 MAY 2026',
    duration: 'TBA',
    youtubeId: 'mN5FLOsixFc',
    spotifyUrl: 'https://open.spotify.com/playlist/3UmKMhYsJXRqzUygP37ihw',
    beatportUrl: 'https://www.beatport.com/de/chart/music-radar-001/890903',
    tracks: [
      { n: '01', title: 'Trigger Finger',   artist: 'James Hype',                          bpm: 128, key: 'A Minor', genre: 'Tech House',      cue: '00:00' },
      { n: '02', title: 'Free Your Mind',   artist: 'Prospa & Cloonee',                    bpm: 128, key: 'G Major', genre: 'Progressive House', cue: '00:00' },
      { n: '03', title: 'Talk To You',      artist: 'ANOTR feat. 54 Ultra',                bpm: 126, key: 'F Minor', genre: 'Tech House',      cue: '00:00' },
      { n: '04', title: 'Freaky 1',         artist: 'Vintage Culture, Max Styler & Ali Love', bpm: 129, key: 'D Minor', genre: 'Tech House',   cue: '00:00' },
      { n: '05', title: 'Addicted To Bass', artist: 'Dom Dolla & Puretone',                bpm: 130, key: 'C Minor', genre: 'Bass House',      cue: '00:00' },
      { n: '06', title: 'All The Time',     artist: 'John Summit & The Chainsmokers',      bpm: 128, key: 'A Major', genre: 'Tech House',      cue: '00:00' },
      { n: '07', title: 'How Does It Feel', artist: 'Fezzo, Dubdogz & Zaark',              bpm: 130, key: 'E Minor', genre: 'Bass House',      cue: '00:00' },
      { n: '08', title: 'Neck',             artist: 'Mau P',                               bpm: 131, key: 'G Minor', genre: 'Tech House',      cue: '00:00' },
      { n: '09', title: 'One More',         artist: 'Max Styler, Ad-Apt & Solomun',        bpm: 124, key: 'D Minor', genre: 'Melodic House',   cue: '00:00' },
      { n: '10', title: 'Back To The 305',  artist: 'Omar+ & Luke Dean',                   bpm: 126, key: 'F Major', genre: 'House',           cue: '00:00' },
    ]
  },
];


window.GRINLOUD_DATA = { PICKS, RADAR, PREVIOUS_RADARS, BG_VIDEOS, NEWSLETTER };
